name: Update Formula
on:
  repository_dispatch:
    types: [released]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Dump Values
        run: |
          echo ${{ github.event.client_payload.sha256 }}
          echo ${{ github.event.client_payload.binary }}
          echo ${{ github.event.client_payload.url }}
          echo ${{ github.event.client_payload.desc }}
          echo ${{ github.event.client_payload.ref }}
