name: Update Formula
on:
  repository_dispatch:
    types: [released]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Dump Values
        run: |
          echo ${{ github.event.client_payload.sha256 }}
          echo ${{ github.event.client_payload.binary }}
          echo ${{ github.event.client_payload.class }}
          echo ${{ github.event.client_payload.url }}
          echo ${{ github.event.client_payload.ref }}
          binary=${{ github.event.client_payload.binary }}
          ref=${{ github.event.client_payload.ref }}
          url="https://github.com/Rasukarusan/$binary/releases/download/$ref/$binary"
          echo $url
      - name: Dump Values
        run: |
          data=$(cat <<EOF
            class ${{ github.event.client_payload.class }} < Formula
              url "${{ github.event.client_payload.url }}"
              sha256 "${{ github.event.client_payload.sha256 }}"
              def install
                bin.install "${{ github.event.client_payload.binary }}"
              end
            end
          EOF
          )
          echo "$data"
